--Criacao das bases e tabelas para teste.

CREATE DATABASE TESTE;
CREATE DATABASE TESTE2;

CREATE TABLE TESTE.PEOPLE(
ID INTEGER NOT NULL AUTO_INCREMENT ,
NAME VARCHAR(100) NOT NULL , 
AGE INTEGER NOT NULL ,
PRIMARY KEY ( ID )
);


CREATE TABLE TESTE2.PEOPLE(
ID INTEGER NOT NULL AUTO_INCREMENT ,
NAME VARCHAR(100) NOT NULL , 
AGE INTEGER NOT NULL ,
PRIMARY KEY ( ID )
);

